(load "test-driver.scm")
(load "tests-1.1-req.scm")

(define (compile-program x)
  (unless (integer? x) (error ---))
  (emit "    .section        __TEXT,__text,regular,pure_instructions")
  (emit "    .global _scheme_entry")
  (emit "    .align  4, 0x90")
  (emit "_scheme_entry:        ## @scheme_entry")
  (emit "    .cfi_startproc")
  (emit "## BB#0:")
  (emit "    movl $~s, %eax" x)
  (emit "    ret")
  (emit "    .cfi_endproc"))
